-- Jalankan di Supabase SQL Editor
create table public.news (
 id bigint generated by default as identity primary key,
 title text not null, category text default 'KEGIATAN',
 description text, image_url text, author_id uuid references auth.users(id),
 created_at timestamptz default now()
);
create table public.agenda (
 id bigint generated by default as identity primary key,
 title text not null, event_date date not null, location text,
 created_at timestamptz default now()
);
alter table public.news enable row level security;
alter table public.agenda enable row level security;
create policy "public read news" on public.news for select using (true);
create policy "public read agenda" on public.agenda for select using (true);
create policy "admin insert news" on public.news for insert to authenticated with check (auth.uid()=author_id);
create policy "admin delete news" on public.news for delete to authenticated using (auth.uid()=author_id);
create policy "admin insert agenda" on public.agenda for insert to authenticated with check (true);
create policy "admin delete agenda" on public.agenda for delete to authenticated using (true);
-- Buat Storage bucket bernama: news-images, set Public bucket.
